id: P005417
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4598
  title: བྱེ་བྲག་རྟོགས་བྱེད་ཆེན་མོ།
  author: ''
  volumes:
    c7b1c51024eb4769883b1a2bb3ae6e05:
      image_group_id: I1KG5113
      title: ''
      volume_number: 1
      total_pages: 686
      base_file: v001.txt
    1471850a0600436fb15777d897bc694b:
      image_group_id: I1KG5114
      title: ''
      volume_number: 2
      total_pages: 524
      base_file: v002.txt
