id: I29B49B79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:01:21+00:00'
last_modified: '2022-06-08T02:56:18.424344+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4598
  title: བྱེ་བྲག་རྟོགས་བྱེད་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0096:
      image_group_id: I1KG5113
      title: ''
      total_pages: 686
      order: 1
      base_file: 0096.txt
    CA4A:
      image_group_id: I1KG5114
      title: ''
      total_pages: 524
      order: 2
      base_file: CA4A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
